In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[21, 43],
       [20, 22],
       [68,  3],
       [24, 54],
       [50, 82],
       [66, 63],
       [60, 16],
       [76,  0],
       [ 0, 73],
       [ 3, 14]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/Users/ming/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

this warning is about int to floating point, when scaling to fits our model

In [8]:
scaler_model.transform(data)

array([[ 0.27631579,  0.52439024],
       [ 0.26315789,  0.26829268],
       [ 0.89473684,  0.03658537],
       [ 0.31578947,  0.65853659],
       [ 0.65789474,  1.        ],
       [ 0.86842105,  0.76829268],
       [ 0.78947368,  0.19512195],
       [ 1.        ,  0.        ],
       [ 0.        ,  0.8902439 ],
       [ 0.03947368,  0.17073171]])

In [9]:
scaler_model.fit_transform(data)

/Users/ming/anaconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.27631579,  0.52439024],
       [ 0.26315789,  0.26829268],
       [ 0.89473684,  0.03658537],
       [ 0.31578947,  0.65853659],
       [ 0.65789474,  1.        ],
       [ 0.86842105,  0.76829268],
       [ 0.78947368,  0.19512195],
       [ 1.        ,  0.        ],
       [ 0.        ,  0.8902439 ],
       [ 0.03947368,  0.17073171]])

以上两行合并成1行用fit_transflorm

In [13]:
import pandas as pd

In [15]:
mydata = np.random.randint(0,101,(50,4))

In [16]:
mydata

array([[ 19,  16,  68,  97],
       [ 56,  33,  37,  80],
       [ 51,  86,  40,  85],
       [ 40,  21,  63,   0],
       [ 43,  18,  50,  60],
       [ 25,  53,  66,  19],
       [ 45,  65,  68,  98],
       [ 47,  34,  47,  20],
       [ 59,  83,  68, 100],
       [  9,  62,  59,  16],
       [ 89,  45,  98,  66],
       [ 10,  82,  79,  25],
       [ 74,  25,  47,  59],
       [ 57,  50,  28,   8],
       [ 95,  22,  92,   9],
       [ 15,  66,  84,  91],
       [ 94,  47,  70,  61],
       [  3,  40,  60,  36],
       [ 94,  26,  58,  38],
       [ 35,  12,  22,  48],
       [ 63,  76,  16,  85],
       [ 48,  54,   4,  23],
       [ 76,  14,  72,  17],
       [  2,   7,  81,  54],
       [ 34,  61,  48,  86],
       [  1,  56,  35,  82],
       [ 40,  14,  15,  15],
       [ 41,  62,  60,  33],
       [ 83,   2,  99,  65],
       [ 98,  46,  54,  46],
       [ 14,  61,   5,   7],
       [ 29,  44,  48,  15],
       [ 83,  76,   3,   4],
       [ 85,  91,  27,  11],
       [ 66,  

In [24]:
df = pd.DataFrame(data=mydata, columns = ['f1','f2','f3','label'])

In [25]:
df

f1  f2   f3  label
0   19  16   68     97
1   56  33   37     80
2   51  86   40     85
3   40  21   63      0
4   43  18   50     60
5   25  53   66     19
6   45  65   68     98
7   47  34   47     20
8   59  83   68    100
9    9  62   59     16
10  89  45   98     66
11  10  82   79     25
12  74  25   47     59
13  57  50   28      8
14  95  22   92      9
15  15  66   84     91
16  94  47   70     61
17   3  40   60     36
18  94  26   58     38
19  35  12   22     48
20  63  76   16     85
21  48  54    4     23
22  76  14   72     17
23   2   7   81     54
24  34  61   48     86
25   1  56   35     82
26  40  14   15     15
27  41  62   60     33
28  83   2   99     65
29  98  46   54     46
30  14  61    5      7
31  29  44   48     15
32  83  76    3      4
33  85  91   27     11
34  66  55   62     99
35  61  97   33     61
36   1  61   58     16
37  94  87  100     23
38  85  91   81     66
39  47  12   92     94
40  67  48   23     41
41  54  40   90    100
42  88  20   42     47
43  89  88   47      4
44  19  19    9     47
45  24  57   20      4
46  59  77   52     17
47  54  66   50     22
48  41  62   97     57
49  63  89   40     30

In [26]:
X = df[['f1','f2','f3']]

In [28]:
y = df['label']

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.3, random_state=42)

test size usually 33%, shift tab and scroll down to copy past this

In [31]:
X_train.shape

(35, 3)

In [32]:
X_test.shape

(15, 3)